In [1]:
from api import VisualizerApp

In [2]:
v = VisualizerApp()

In [ ]:
latex_expression = "e^{x + y}"
# aaaarrrrrgggggghgghhhhhhhhhhhh!!!!!!!!!!!!!!
from latex2sympy2 import latex2sympy as lts
import numpy as np
import sympy as sp

sympy_expr = lts(latex_expression)
print(sympy_expr)

# Define the symbolic variables
x, y = sp.symbols('x y')

# Convert the symbolic expression to a callable function
sympy_func = sp.lambdify((x, y), sympy_expr, 'numpy')

# Use the callable function with np.fromfunction
result = np.fromfunction(sympy_func, (3, 3))
print(result)

exp(x + y)
[[ 1.          2.71828183  7.3890561 ]
 [ 2.71828183  7.3890561  20.08553692]
 [ 7.3890561  20.08553692 54.59815003]]


exp(x)


In [10]:
sympy_expr_str = str(sympy_expr)
sympy_expr_str

'exp(x)'

In [14]:
np.fromfunction(sympy_expr, (3,3))

TypeError: 'exp' object is not callable

In [15]:
import numpy as np
import sympy as sp

# Define the symbolic expression
x, y = sp.symbols('x y')
sympy_expr = sp.exp(x + y)

# Convert the symbolic expression to a callable function
sympy_func = sp.lambdify((x, y), sympy_expr, 'numpy')

# Use the callable function with np.fromfunction
result = np.fromfunction(sympy_func, (3, 3))
print(result)

[[ 1.          2.71828183  7.3890561 ]
 [ 2.71828183  7.3890561  20.08553692]
 [ 7.3890561  20.08553692 54.59815003]]
